version: '3.7'

services:

  esdb:
    container_name: eventuous-esdb
    image: eventstore/eventstore:latest
    ports:
      - '2113:2113'
      - '1113:1113'
    environment:
      EVENTSTORE_INSECURE: 'true'
      EVENTSTORE_CLUSTER_SIZE: 1
      EVENTSTORE_EXT_TCP_PORT: 1113
      EVENTSTORE_HTTP_PORT: 2113
      EVENTSTORE_ENABLE_EXTERNAL_TCP: 'true'
      EVENTSTORE_RUN_PROJECTIONS: all
      EVENTSTORE_START_STANDARD_PROJECTIONS: "true"
      EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP: "true"

  sql:
    container_name: conduit-sql
    image: mcr.microsoft.com/azure-sql-edge
    ports:
      - '1433:1433'
    environment: 
      ACCEPT_EULA: Y
      SA_PASSWORD: P@ssw0rd
      
networks:
  default:
    name: eventuous-network
