version: '3.7'

services:
  sql:
    container_name: conduit-sql
    image: mcr.microsoft.com/azure-sql-edge
    ports:
      - '1433:1433'
    environment: 
      ACCEPT_EULA: Y
      SA_PASSWORD: P@ssw0rd
